server:
  port: 18081
spring:
  application:
    name: changgou-goods
  datasource:
    url: jdbc:mysql://192.168.5.125:3306/changgou_goods?useUnicode=true&characterEncoding=UTF‐8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
eureka:
  instance:
    hostname: 127.0.0.1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.client.eureka-server-port}/eureka
    eureka-server-port: 6868
feign:
  hystrix:
    enabled: true
         
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.bowen.service.goods.api.pojo